version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  cypress:
    image: cypress/included:8.7.0
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /dev/shm:/dev/shm
